export default {
  inputPayout: [
    {
      name: "beneficiary_name",
      label: "Nama Lengkap",
      description: "Nama lengkap sesuai nama pada akun rekening",
      type: "text",
      value: "",
      placeholder: "",
      required: true,
    },
    {
      name: "beneficiary_email",
      label: "Alamat Email",
      description: "Bukti transaksi akan dikirim ke email yang dicantumkan",
      type: "email",
      value: "",
      placeholder: "",
      required: true,
    }, 
    {
      name: "beneficiary_bank",
      label: "Bank Tujuan",
      type: "select",
      value: 0,
      placeholder: "",
      options: [],
      required: true,
    },
    {
      name: "beneficiary_account",
      label: "Nomor Akun Rekening",
      description: "Nomor rekening akan disamarkan",
      type: "text",
      value: "",
      placeholder: "",
      required: true,
    },
    {
      name: "amount",
      label: "Jumlah Uang (Rp)",
      description: "Minimal Rp10.000",
      min: 10000,
      type: "currency",
      value: 0,
      placeholder: "",
    },
  ],
};
