export default {
    inputProfile: [
        { name: 'photo', label: 'Foto Profil', type: 'image', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap', type: 'text', value: '', placeholder: '', required: false },
        { name: 'birthDate', label: 'Tanggal Lahir', type: 'date', value: '', placeholder: '', required: true },
        { name: 'phone', label: 'Nomor Telepon', type: 'text', value: '', placeholder: '', required: false },
        { name: 'bio', label: 'Bio', type: 'text', value: '', placeholder: '', required: false },
        { name: 'address', label: 'Alamat Lengkap', type: 'textarea', value: '', placeholder: '', required: false },
        { name: 'github', label: 'Github', type: 'text', value: '', placeholder: 'https://github.com/username', required: false },
        { name: 'linkedIn', label: 'LinkedIn', type: 'text', value: '', placeholder: 'https://www.linkedin.com/in/username', required: false },
        { name: 'password', label: 'Password', type: 'password', value: '', placeholder: '', required: false },
        // { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        // { name: 'portfolio', label: 'Tambahkan Rapor', type: 'file', value: '', placeholder: '', required: false },
        // { name: 'raport', label: 'Tambahkan Portofolio', type: 'file', value: '', placeholder: '', required: false },
        // { name: 'onlineCv', label: 'Tambahkan CV', type: 'file', value: '', placeholder: '', required: false },
    ],
    inputFormUser: [
        { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'city', label: 'Asal Kota *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'school', label: 'Sekolah', type: 'text', value: '', placeholder: '', required: false },
        { name: 'raport', label: 'Tambahkan Rapor *', type: 'file', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
    inputFormAdmin: [
        { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'bio', label: 'Bio', type: 'textarea', value: '', placeholder: '', required: false },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'portofolio', label: 'Portofolio', type: 'text', value: '', placeholder: '', required: false },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
    inputFormMentor: [
        { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'bio', label: 'Bio', type: 'textarea', value: '', placeholder: '', required: false },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'portofolio', label: 'Portofolio', type: 'text', value: '', placeholder: 'Maybe Github', required: false },
        { name: 'online_cv', label: 'Online CV', type: 'text', value: '', placeholder: 'Maybe LinkedIn', required: false },
        { name: 'job', label: 'Pekerjaan', type: 'text', value: '', placeholder: '', required: false },
        { name: 'institution', label: 'Institusi', type: 'text', value: '', placeholder: '', required: false },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
    inputFormIndustry: [
        { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'city', label: 'Asal Kota *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
}