export default {
    tables: {
        user: [
            { key: "no", label: 'No'},
            { key: "name", label: `Nama Lengkap`},
            { key: "email", label: "Alamat Email" },
            { key: "status", label: "Stat" },
            { key: "action", label: " ", _classes: "text-right" },
        ],
        studentRequest: [
            { key: "index", label: 'No' },
            { key: 'name', label: 'Nama Lengkap'},
            { key: 'email', label: 'Kontak'},
            // { key: 'nik', label: 'NIK', },
            // { key: 'phone', label: 'No Handphone' },
            // { key: 'program', label: 'Program'},
            { key: 'origin', label: 'Asal'},
            // { key: 'verified', label: 'Status', sortable: true, },
            { key: 'action', label: '', class: 'text-right' }
        ],
    },
    // inputFormUser: [        
    //     { name: 'name', label: 'Nama Lengkap', type: 'text', value: '', placeholder: '', required: true },
    //     { name: 'email', label: 'Alamat Email', type: 'email', value: '', placeholder: '', required: true },
    //     { name: 'kindId', label: 'Jenis User', type: 'select', value: '', placeholder: '', required: true },
    //     { name: 'programId', label: 'Program', type: 'select', value: '', placeholder: '', required: true },
    //     { name: 'password', label: 'Password', type: 'password', value: '', placeholder: '', required: true },
    //     { name: 'retypepassword', label: 'Tulis Ulang Password', type: 'password', value: '', placeholder: '', required: true },
    // ],
    inputCommonUser: [
        { name: 'kind', label: 'User Role *', type: 'select', value: '', placeholder: '', required: true },

        // { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true, min: 8 },
        // { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        // { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'gender', label: 'Jenis Kelamin *', type: 'select', value: '', placeholder: '', required: true },        
        { name: 'regionId', label: 'Pilih Region *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'programId', label: 'Pilih program *', type: 'select', value: '', placeholder: '', required: true },
        // { name: 'bio', label: 'Bio', type: 'textarea', value: '', placeholder: '', required: false },
        // { name: 'portfoliio', label: 'Portfolio', type: 'text', value: '', placeholder: '', required: false },
        // { name: 'onlineCv', label: 'Online CV', type: 'text', value: '', placeholder: '', required: false },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
        { name: 'retypepassword', label: 'Ketik Ulang Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
    inputFormStudent: [
        // { name: 'kind', label: 'User Role *', type: 'select', value: '', placeholder: '', required: true },

        // { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        // { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        // { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        // { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        // { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        // { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        // { name: 'gender', label: 'Jenis Kelamin *', type: 'select', value: '', placeholder: '', required: true },
        // { name: 'bio', label: 'Bio', type: 'textarea', value: '', placeholder: '', required: false },
        // { name: 'portfoliio', label: 'Portfolio', type: 'text', value: '', placeholder: '', required: false },
        // { name: 'onlineCv', label: 'Online CV', type: 'text', value: '', placeholder: '', required: false },
        // { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
        // { name: 'retypepassword', label: 'Tulis Ulang Password *', type: 'password', value: '', placeholder: '', required: true },

        { name: 'city', label: 'Asal Kota *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'transcriptFile', label: 'Tambahkan Rapor', type: 'file', value: '', placeholder: '', required: false },
        { name: 'certificate', label: 'Tambahkan Ijazah *', type: 'file', value: '', placeholder: '', required: true },
        { name: 'statementLetter', label: 'Tambahkan Surat Keterangan *', type: 'file', value: '', placeholder: '', required: true },
    ],
    inputFormAdmin: [
        // { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        // { name: 'ktp', label: 'KTP *', type: 'file', value: '', placeholder: '', required: true },
        { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'gender', label: 'Jenis Kelamin *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'role', label: 'Jenis Admin *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'bio', label: 'Bio', type: 'text', value: '', placeholder: '', required: false },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'program', label: 'Program *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'online_cv', label: 'Online CV', type: 'text', value: '', placeholder: 'Maybe LinkedIn', required: false },
        { name: 'job', label: 'Pekerjaan', type: 'text', value: '', placeholder: '', required: false },
        { name: 'institution', label: 'Institusi', type: 'text', value: '', placeholder: '', required: false },
        { name: 'portofolio', label: 'Portofolio', type: 'text', value: '', placeholder: '', required: false },
        { name: 'city', label: 'Asal Kota *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
        { name: 'retypepassword', label: 'Ketik ulang Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
    inputFormMentor: [
        { name: 'photo', label: 'Tambahkan Foto', type: 'file', value: '', placeholder: '', required: false },
        { name: 'name', label: 'Nama Lengkap *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        // { name: 'ktp', label: 'KTP *', type: 'file', value: '', placeholder: '', required: true },
        { name: 'nik', label: 'NIK *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'bio', label: 'Bio', type: 'text', value: '', placeholder: '', required: false },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'portofolio', label: 'Portofolio', type: 'text', value: '', placeholder: 'Maybe Github', required: false },
        { name: 'online_cv', label: 'Online CV', type: 'text', value: '', placeholder: 'Maybe LinkedIn', required: false },
        { name: 'job', label: 'Pekerjaan', type: 'text', value: '', placeholder: '', required: false },
        { name: 'institution', label: 'Institusi', type: 'text', value: '', placeholder: '', required: false },
        { name: 'program', label: 'Program *', type: 'select', placeholder: '', value: 0, required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
        { name: 'retypepassword', label: 'Tulis Ulang Password *', type: 'password', value: '', placeholder: '', required: true },
        { name: 'gender', label: 'Jenis Kelamin *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'status', label: 'Status *', type: 'select', value: '', placeholder: '', required: true },
    ],
    inputFormIndustries: [
        { name: 'name', label: 'Nama Dinas / Industri *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'address', label: 'Alamat *', type: 'text', value: '', placeholder: '', required: true },
        { name: 'city', label: 'Asal Kota *', type: 'select', value: '', placeholder: '', required: true },
        { name: 'phone', label: 'Nomor Telepon *', type: 'number', value: '', placeholder: '', required: true },
        { name: 'email', label: 'Alamat Email *', type: 'email', value: '', placeholder: '', required: true },
        { name: 'password', label: 'Password *', type: 'password', value: '', placeholder: '', required: true },
        { name: 'retypepassword', label: 'Tulis Ulang Password *', type: 'password', value: '', placeholder: '', required: true },
    ],
}