import { DEFAULT_PAGE } from "./setting-page";

const student = [
    '/',
    'dashboard',
    'dashboard-classroom',
    'dashboard-classroom-Requirements-code',
    'dashboard-schedules',
    'dashboard-classroom-classroom',
    'dashboard-classroom-history',
    'dashboard-classroom-overview-code',
    'dashboard-classroom-classroom-course-course-module-module',
    'dashboard-classroom-classroom-course-course-module-module',
    'dashboard-classroom-classroom-assignment-assignment',
    'dashboard-classroom-classroom-event-event',
    'dashboard-schedules-id',
    'dashboard-classroom-Assignments-classroomId',
    'dashboard-tes',
    'dashboard-tes-Requirements-code',
    'dashboard-tes-classroom',
    'dashboard-tes-history',
    'dashboard-tes-overview-code',
    'dashboard-tes-classroom-course-course-module-module',
    'dashboard-tes-classroom-course-course-module-module',
    'dashboard-tes-assignments-classroomId',
    'dashboard-certificate',
    'dashboard-certificate-classSlug-view-classroomId',
    'dashboard-rapor',
    'dashboard-profile-raport-classSlug',
    'dashboard-students-detail-certificate-classSlug-view-classroomId',
    'dashboard-students-detail-raport-classSlug-view-classroomId',
    'dashboard-profile',
    'dashboard-profile-edit',
    'Dashboard-Profile-Certificate-classSlug-View-classroomId',
    'Dashboard-Profile-Raport-classSlug-View-classroomId',
    'Dashboard-Achievement',
    'Dashboard-Classroom-classroom-pretest',
    'Dashboard-Classroom-classroom-course-course',
    'Dashboard-Classroom-classroom-course-course-assignment-assignment',
]

const mentor = [
    '/',
    'dashboard',
    'dashboard-schedules',
    'dashboard-classroom',
    'dashboard-classroom-draft',
    'dashboard-classroom-classroom',
    'dashboard-classroom-classroom-leaderboard',
    'dashboard-classroom-classroom-course-course-module-module',
    'dashboard-classroom-classroom-course-course-module-module-scoring-userId',
    'dashboard-classroom-overview-code',
    'dashboard-classroom-assignments-classroomId',
    'dashboard-classroom-assignments-classroomId-create',
    'dashboard-classroom-assignments-classroomId-edit-topicId',
    'dashboard-classroom-classroom-assignment-assignment',
    'dashboard-classroom-classroom-event-event',
    'dashboard-schedules-id',
    'Dashboard-Classroom-Students-classroomId',
    'dashboard-tes',
    'dashboard-tes-draft',
    'dashboard-tes-classroom',
    'dashboard-tes-classroom-leaderboard',
    'dashboard-tes-classroom-course-course-module-module',
    'dashboard-tes-classroom-course-course-module-module-scoring-userId',
    'dashboard-tes-overview-code',
    'dashboard-tes-assignments-classroomId',
    'dashboard-tes-assignments-classroomId-create',
    'dashboard-tes-assignments-classroomId-edit-topicId',
    'Dashboard-tes-Students-classroomId',
    'dashboard-students-detail',
    'dashboard-students-detail-raport-classSlug',
    'dashboard-students-detail-raport-classSlug-view-classroomId',
    'dashboard-students-detail-certificate-classSlug-view-classroomId',
    'Dashboard-Profile',
    'Dashboard-Profile-edit',
    'Dashboard-Reviews',
    'Dashboard-Classroom-classroom-course-course',
    'Dashboard-Statistic',
    "Dashboard-Classroom-classroom-event-event-attendance-recap",
    "Dashboard-Classroom-classroom-event-event-attendance-create",
    'Dashboard-Statistic',
]

const writer = [
    '/',
    'Dashboard',
    'Dashboard-Schedules',
    'Dashboard-Blog',
    'Dashboard-Blog-Create',
    'Dashboard-Blog-id',
    'Dashboard-Blog-Edit-id',
    'Dashboard-Galleries',
    'Dashboard-Galleries-Create',
    'Dashboard-Galleries-id',
    'Dashboard-Galleries-Edit-id',
    'Dashboard-Profile',
    'Dashboard-Profile-edit',
    'Dashboard-Announcement',
    'Dashboard-Announcement-Create',
    'Dashboard-Announcement-Edit-edit',
    'Dashboard-Program',
    'Dashboard-Program-Create',
    'Dashboard-Program-Edit-edit',
    'Dashboard-Career',
    'Dashboard-Career-Create',
    'Dashboard-Career-Edit-edit',
    'Dashboard-Testimonies',
    'Dashboard-Testimonies-Create',
    'Dashboard-Testimonies-Edit-edit',
    'Dashboard-Testimonies'
]

const lead_program = [
    "Dashboard",
    "Dashboard-Schedules",
    "Dashboard-Courses",
    "Dashboard-Courses-Pretest",
    "Dashboard-Courses-Create",
    "Dashboard-Courses-Edit-edit",
    "Dashboard-Courses-Modules-courseId",
    "Dashboard-Courses-Modules-courseId-Create-create",
    "Dashboard-Courses-Modules-courseId-Edit-edit",
    "Dashboard-Courses-Modules-courseId-Detail-detail",
    "Dashboard-Students-detail",
    "Dashboard-Students-detail-Raport-classSlug",
    "Dashboard-Students-detail-Raport-classSlug-View-classroomId",
    "Dashboard-Students-detail-Certificate-classSlug-View-classroomId",
    "Dashboard-Classroom",
    "Dashboard-Classroom-Draft",
    "Dashboard-Classroom-Students-classroomId",
    "Dashboard-Classroom-classroom",
    "Dashboard-Classroom-classroom-course-course-module-module",
    "Dashboard-Classroom-classroom-Leaderboard",
    "Dashboard-Classroom-classroom-course-course-module-module-scoring-userId",
    "Dashboard-Classroom-Assignments-classroomId",
    "Dashboard-Classroom-Assignments-classroomId-Create",
    "Dashboard-Classroom-Assignments-classroomId-Edit-topicId",
    "Dashboard-Tes",
    "Dashboard-Tes-Draft",
    "Dashboard-Tes-Students-classroomId",
    "Dashboard-Tes-classroom",
    "Dashboard-Tes-classroom-course-course-module-module",
    "Dashboard-Tes-classroom-Leaderboard",
    "Dashboard-Tes-classroom-course-course-module-module-scoring-userId",
    "Dashboard-Tes-Assignments-classroomId",
    "Dashboard-Tes-Assignments-classroomId-Create",
    "Dashboard-Tes-Assignments-classroomId-Edit-topicId",
    "Dashboard-Profile",
    "Dashboard-Profile-edit",
    'dashboard-classroom-classroom-assignment-assignment',
    'dashboard-classroom-classroom-event-event',
    'dashboard-schedules-id',
    "Dashboard-Recap",
    "Dashboard-Reviews",
]

const lead_region = [
    'Dashboard',
    'Dashboard-Schedules',
    'Dashboard-Users',
    'Dashboard-Classroom',
    'Dashboard-Classroom-classroom',
    'Dashboard-Classroom-classroom-course-create',
    'Dashboard-Classroom-classroom-course-course-edit',
    'Dashboard-Classroom-classroom-module-module-edit',
    'Dashboard-Classroom-classroom-course-course-module-module',
    'Dashboard-Classroom-classroom-module-create',
    'Dashboard-Classroom-classroom-assignment-create',
    'Dashboard-Classroom-classroom-assignment-assignment',
    'Dashboard-Classroom-classroom-assignment-assignment-edit',
    'Dashboard-Classroom-classroom-event-create',
    'Dashboard-Classroom-classroom-event-event-edit',
    'Dashboard-Classroom-Create',
    'Dashboard-Classroom-Edit-edit',
    'Dashboard-Students-detail',
    'Dashboard-Students-detail-Raport-classSlug',
    'Dashboard-Students-detail-Raport-classSlug-View-classroomId',
    'Dashboard-Students-detail-Certificate-classSlug-View-classroomId',
    'Dashboard-Reviews',
    'Dashboard-Recap',
    'Dashboard-Profile',
    'Dashboard-Profile-edit',
    'dashboard-classroom-classroom-assignment-assignment',
    'dashboard-classroom-classroom-event-event',
    'dashboard-schedules-id',
    'Dashboard-Statistic',
]

const teacher = [
    '/',
    'dashboard',
    'dashboard-schedules',
    'dashboard-classroom',
    'dashboard-classroom-draft',
    'dashboard-classroom-classroom',
    'dashboard-classroom-classroom-leaderboard',
    'dashboard-classroom-classroom-course-course-module-module',
    'dashboard-classroom-classroom-course-course-module-module-scoring-userId',
    'dashboard-classroom-overview-code',
    'dashboard-classroom-assignments-classroomId',
    'dashboard-classroom-assignments-classroomId-create',
    'dashboard-classroom-assignments-classroomId-edit-topicId',
    'dashboard-classroom-classroom-assignment-assignment',
    'dashboard-classroom-classroom-event-event',
    'dashboard-schedules-id',
    'Dashboard-Classroom-Students-classroomId',
    'dashboard-tes',
    'dashboard-tes-draft',
    'dashboard-tes-classroom',
    'dashboard-tes-classroom-leaderboard',
    'dashboard-tes-classroom-course-course-module-module',
    'dashboard-tes-classroom-course-course-module-module-scoring-userId',
    'dashboard-tes-overview-code',
    'dashboard-tes-assignments-classroomId',
    'dashboard-tes-assignments-classroomId-create',
    'dashboard-tes-assignments-classroomId-edit-topicId',
    'Dashboard-tes-Students-classroomId',
    'dashboard-students-detail',
    'dashboard-students-detail-raport-classSlug',
    'dashboard-students-detail-raport-classSlug-view-classroomId',
    'dashboard-students-detail-certificate-classSlug-view-classroomId',
    'Dashboard-Profile',
    'Dashboard-Profile-edit',
    'Dashboard-Classroom-classroom-course-course',
    'Dashboard-Statistic',
    'Dashboard-Classroom-classroom-course-course-assignment-assignment',,
    'Dashboard-Recap',
]

const REDIRECT_ROUTE = [
    {
        routeName: "Dashboard",
        newPath: DEFAULT_PAGE,
        roles: ["superadmin", "admin", "mentor", "lead_program", "student", "teacher", "lead_region"],
    },
    {
        routeName: "Dashboard-Statistic",
        newPath: DEFAULT_PAGE,
        roles: ["student"],
    }
]


const route = [
    {
        title: 'dashboard',
        name: 'dashboard',
        role: ['all']
    },
    {
        title: 'Kelas',
        name: 'dashboard-classroom',
        role: ['student']
    },
    {
        title: 'Detail Kelas / Tugas',
        name: 'dashboard-classroom-classroom',
        role: ['student']
    },
    {
        title: 'Detail Modul',
        name: 'Dashboard-Classroom-classroom-course-course-module-module',
        role: ['student']
    },
    {
        title: 'Tugas',
        name: 'Dashboard-Classroom-Assignments-classroomId',
        role: ['student']
    },
]

export default {
    lead_region,
    lead_program,
    student,
    writer,
    mentor,
    REDIRECT_ROUTE,
    teacher
}